GET http://localhost:3000/user

###

POST http://localhost:3000/user

Content-Type: application/json

{
    "userName": "first_user",
    "firstName": "First",
    "lastName": "User",
    "password": "1234",
    "email": "firstuser@gmail.com"
}